server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

spring:
  application:
    name: ms-football-team
  main:
    webApplicationType: reactive